### ISSUE TITLE
Auth.py error

### ISSUE THREAD

**Issue by Redemption777** [highlowapp/Authentication#11]
There is an error in the Auth.py code in line 46
The code:
`token_list = cursor.fetchall()`

The error:
`pymysql.err.ProgrammingError: execute() first`

[This person](https://stackoverflow.com/questions/34337452/mysqldb-raises-execute-first-error-even-though-i-execute-before-calling-fetc) said that it is because there are multiple cursors, but when I looked at it I didn't see multiple cursors. Any ideas?

**Comment by Redemption777** [comment]
Also I added `print("before suspected error")` and `print("after suspected error")` before and after that line to test for sure if that was the line with the error. I could see the output `before suspected error` but not `after suspected error`. That's how I knew the error was on that line.

**Comment by naclcaleb** [comment]
Hmm...I'll look into that.

**Comment by naclcaleb** [comment]
I'm not getting any errors when I start up the server. 

I might need to know a bit more about your development environment. Where is the `init` function being called?

**Comment by naclcaleb** [comment]
Although I am getting `OperationalError: (2003, "Can't connect to MySQL server on u'box2018.temp.domains' (timed out)")`. I'm not sure why.

**Comment by naclcaleb** [comment]
This may be unrelated, but it turns out we might need to add nginx as the web server for our production environment: https://vsupalov.com/flask-web-server-in-production/

**Comment by naclcaleb** [comment]
We may have to switch the MySQL database to being hosted on the Google server. This will take up more disk space and processing power, but it will probably be more reliable.

**Comment by naclcaleb** [comment]
Try building the image via the `build.py` script. 
You'll have to delete your current `services` folder first or it might not work.
